// <auto-generated />
using System;
using InventoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318194449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryAPI.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Alerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertType = "OUT_OF_STOCK",
                            CreatedAt = new DateTime(2024, 4, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = false,
                            Message = "'Wireless Mouse' (SKU: AC-002) is out of stock.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 2,
                            AlertType = "LOW_STOCK",
                            CreatedAt = new DateTime(2024, 4, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = false,
                            Message = "'Mechanical Keyboard' (SKU: AC-001) is running low. Current stock: 3 units.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 3,
                            AlertType = "LOW_STOCK",
                            CreatedAt = new DateTime(2024, 4, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = false,
                            Message = "'Stapler Heavy Duty' (SKU: OF-002) is running low. Current stock: 4 units.",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 4,
                            AlertType = "LOW_STOCK",
                            CreatedAt = new DateTime(2024, 4, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = false,
                            Message = "'4-Drawer Filing Cabinet' (SKU: FN-003) is running low. Current stock: 2 units.",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 5,
                            AlertType = "LOW_STOCK",
                            CreatedAt = new DateTime(2024, 3, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = true,
                            Message = "'Wireless Mouse' (SKU: AC-002) was running low. Stock: 10 units.",
                            ProductId = 5,
                            ResolvedAt = new DateTime(2024, 4, 6, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AlertType = "LOW_STOCK",
                            CreatedAt = new DateTime(2024, 2, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = true,
                            Message = "'A4 Paper Ream' (SKU: OF-001) was running low.",
                            ProductId = 9,
                            ResolvedAt = new DateTime(2024, 3, 3, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices, gadgets and components",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Stationery, paper and office essentials",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Office and warehouse furniture",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Routers, switches, cables and networking gear",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Peripheral devices and accessories",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "8901234567890",
                            CategoryId = 1,
                            CostPrice = 980.00m,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dell Inspiron 15, Intel i7, 16GB RAM, 512GB SSD",
                            IsActive = true,
                            LowStockThreshold = 5,
                            Name = "Dell Laptop 15\"",
                            Price = 1299.99m,
                            QuantityInStock = 25,
                            SKU = "EL-001",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8901234567891",
                            CategoryId = 1,
                            CostPrice = 240.00m,
                            CreatedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HP LaserJet Pro M404dn, 40 ppm",
                            IsActive = true,
                            LowStockThreshold = 5,
                            Name = "HP LaserJet Printer",
                            Price = 349.99m,
                            QuantityInStock = 8,
                            SKU = "EL-002",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "8901234567892",
                            CategoryId = 1,
                            CostPrice = 310.00m,
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Samsung 27\" 4K UHD IPS Monitor",
                            IsActive = true,
                            LowStockThreshold = 4,
                            Name = "Samsung Monitor 27\"",
                            Price = 429.99m,
                            QuantityInStock = 14,
                            SKU = "EL-003",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "8901234567893",
                            CategoryId = 5,
                            CostPrice = 55.00m,
                            CreatedAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Logitech MX Keys Mechanical, Wireless",
                            IsActive = true,
                            LowStockThreshold = 5,
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            QuantityInStock = 3,
                            SKU = "AC-001",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "8901234567894",
                            CategoryId = 5,
                            CostPrice = 28.00m,
                            CreatedAt = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Logitech MX Master 3 Wireless Mouse",
                            IsActive = true,
                            LowStockThreshold = 5,
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            QuantityInStock = 0,
                            SKU = "AC-002",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8901234567895",
                            CategoryId = 4,
                            CostPrice = 420.00m,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cisco Catalyst 2960 24-Port Gigabit Switch",
                            IsActive = true,
                            LowStockThreshold = 3,
                            Name = "Cisco Switch 24-Port",
                            Price = 599.99m,
                            QuantityInStock = 6,
                            SKU = "NW-001",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "8901234567896",
                            CategoryId = 4,
                            CostPrice = 78.00m,
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TP-Link AX3000 Dual-Band WiFi 6 Router",
                            IsActive = true,
                            LowStockThreshold = 5,
                            Name = "TP-Link WiFi Router",
                            Price = 129.99m,
                            QuantityInStock = 18,
                            SKU = "NW-002",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "8901234567897",
                            CategoryId = 4,
                            CostPrice = 12.00m,
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cat6 UTP 50m Ethernet Cable, 10Gbps",
                            IsActive = true,
                            LowStockThreshold = 20,
                            Name = "Cat6 Ethernet Cable 50m",
                            Price = 24.99m,
                            QuantityInStock = 80,
                            SKU = "NW-003",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "8901234567898",
                            CategoryId = 2,
                            CostPrice = 5.00m,
                            CreatedAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Navigator A4 80gsm White Paper, 500 sheets",
                            IsActive = true,
                            LowStockThreshold = 30,
                            Name = "A4 Paper Ream 500 Sheets",
                            Price = 8.99m,
                            QuantityInStock = 200,
                            SKU = "OF-001",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "8901234567899",
                            CategoryId = 2,
                            CostPrice = 10.00m,
                            CreatedAt = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rapid Heavy Duty Stapler, 210 sheet capacity",
                            IsActive = true,
                            LowStockThreshold = 5,
                            Name = "Stapler Heavy Duty",
                            Price = 19.99m,
                            QuantityInStock = 4,
                            SKU = "OF-002",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "8901234567900",
                            CategoryId = 2,
                            CostPrice = 6.50m,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expo Dry-Erase Markers, 8-color set",
                            IsActive = true,
                            LowStockThreshold = 10,
                            Name = "Whiteboard Markers Set",
                            Price = 12.99m,
                            QuantityInStock = 45,
                            SKU = "OF-003",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "8901234567901",
                            CategoryId = 3,
                            CostPrice = 270.00m,
                            CreatedAt = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Herman Miller Aeron Style, Lumbar Support, Adjustable",
                            IsActive = true,
                            LowStockThreshold = 3,
                            Name = "Ergonomic Office Chair",
                            Price = 399.99m,
                            QuantityInStock = 10,
                            SKU = "FN-001",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "8901234567902",
                            CategoryId = 3,
                            CostPrice = 380.00m,
                            CreatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electric Height-Adjustable Standing Desk, 160x80cm",
                            IsActive = true,
                            LowStockThreshold = 2,
                            Name = "Standing Desk 160cm",
                            Price = 549.99m,
                            QuantityInStock = 7,
                            SKU = "FN-002",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "8901234567903",
                            CategoryId = 3,
                            CostPrice = 155.00m,
                            CreatedAt = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Steel 4-Drawer Vertical Filing Cabinet with Lock",
                            IsActive = true,
                            LowStockThreshold = 3,
                            Name = "4-Drawer Filing Cabinet",
                            Price = 229.99m,
                            QuantityInStock = 2,
                            SKU = "FN-003",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "8901234567904",
                            CategoryId = 5,
                            CostPrice = 32.00m,
                            CreatedAt = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB-C Hub with HDMI, 3x USB-A, SD Card, 100W PD",
                            IsActive = true,
                            LowStockThreshold = 8,
                            Name = "USB-C Hub 7-in-1",
                            Price = 59.99m,
                            QuantityInStock = 22,
                            SKU = "AC-003",
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 1,
                            Quantity = 30,
                            QuantityAfter = 30,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 2,
                            Quantity = 15,
                            QuantityAfter = 15,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 3,
                            Quantity = 20,
                            QuantityAfter = 20,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 4,
                            Quantity = 15,
                            QuantityAfter = 15,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 5,
                            Quantity = 20,
                            QuantityAfter = 20,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 6,
                            Quantity = 10,
                            QuantityAfter = 10,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 7,
                            Quantity = 25,
                            QuantityAfter = 25,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 8,
                            Quantity = 100,
                            QuantityAfter = 100,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 9,
                            Quantity = 300,
                            QuantityAfter = 300,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 10,
                            Quantity = 20,
                            QuantityAfter = 20,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 11,
                            Quantity = 60,
                            QuantityAfter = 60,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 12,
                            Quantity = 15,
                            QuantityAfter = 15,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 13,
                            Quantity = 10,
                            QuantityAfter = 10,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 14,
                            Quantity = 8,
                            QuantityAfter = 8,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Initial stock received",
                            ProductId = 15,
                            Quantity = 30,
                            QuantityAfter = 30,
                            QuantityBefore = 0,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 2, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sold to Dept. A",
                            ProductId = 1,
                            Quantity = 3,
                            QuantityAfter = 27,
                            QuantityBefore = 30,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 2, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1022",
                            ProductId = 5,
                            Quantity = 8,
                            QuantityAfter = 12,
                            QuantityBefore = 20,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Office weekly supply",
                            ProductId = 9,
                            Quantity = 50,
                            QuantityAfter = 250,
                            QuantityBefore = 300,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 2, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1023",
                            ProductId = 7,
                            Quantity = 4,
                            QuantityAfter = 21,
                            QuantityBefore = 25,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 2, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1024",
                            ProductId = 3,
                            Quantity = 3,
                            QuantityAfter = 17,
                            QuantityBefore = 20,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 2, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "New office setup",
                            ProductId = 12,
                            Quantity = 2,
                            QuantityAfter = 13,
                            QuantityBefore = 15,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 2, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "CEO office upgrade",
                            ProductId = 13,
                            Quantity = 1,
                            QuantityAfter = 9,
                            QuantityBefore = 10,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 2, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1025",
                            ProductId = 15,
                            Quantity = 5,
                            QuantityAfter = 25,
                            QuantityBefore = 30,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 2, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sold to IT dept",
                            ProductId = 2,
                            Quantity = 3,
                            QuantityAfter = 12,
                            QuantityBefore = 15,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 2, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Training room supply",
                            ProductId = 11,
                            Quantity = 10,
                            QuantityAfter = 50,
                            QuantityBefore = 60,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 3, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Restock from TechWorld",
                            ProductId = 5,
                            Quantity = 10,
                            QuantityAfter = 22,
                            QuantityBefore = 12,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 3, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Monthly restock",
                            ProductId = 9,
                            Quantity = 100,
                            QuantityAfter = 350,
                            QuantityBefore = 250,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 3, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Restock order",
                            ProductId = 4,
                            Quantity = 10,
                            QuantityAfter = 25,
                            QuantityBefore = 15,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 3, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Bulk cable purchase",
                            ProductId = 8,
                            Quantity = 50,
                            QuantityAfter = 150,
                            QuantityBefore = 100,
                            TransactionType = "IN",
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 3, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1030",
                            ProductId = 1,
                            Quantity = 2,
                            QuantityAfter = 25,
                            QuantityBefore = 27,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 3, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1031",
                            ProductId = 3,
                            Quantity = 3,
                            QuantityAfter = 14,
                            QuantityBefore = 17,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 3, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1032",
                            ProductId = 5,
                            Quantity = 12,
                            QuantityAfter = 10,
                            QuantityBefore = 22,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "3rd floor office fit-out",
                            ProductId = 12,
                            Quantity = 3,
                            QuantityAfter = 10,
                            QuantityBefore = 13,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Monthly office supply",
                            ProductId = 9,
                            Quantity = 100,
                            QuantityAfter = 250,
                            QuantityBefore = 350,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 3, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Network upgrade project",
                            ProductId = 6,
                            Quantity = 2,
                            QuantityAfter = 8,
                            QuantityBefore = 10,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 3, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1035",
                            ProductId = 7,
                            Quantity = 3,
                            QuantityAfter = 18,
                            QuantityBefore = 21,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 3, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1036",
                            ProductId = 2,
                            Quantity = 4,
                            QuantityAfter = 8,
                            QuantityBefore = 12,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 3, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Stationery replenishment",
                            ProductId = 10,
                            Quantity = 8,
                            QuantityAfter = 12,
                            QuantityBefore = 20,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 3, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1037",
                            ProductId = 15,
                            Quantity = 8,
                            QuantityAfter = 17,
                            QuantityBefore = 25,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 4, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1040 - cleared stock",
                            ProductId = 5,
                            Quantity = 10,
                            QuantityAfter = 0,
                            QuantityBefore = 10,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 4, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1041",
                            ProductId = 4,
                            Quantity = 22,
                            QuantityAfter = 3,
                            QuantityBefore = 25,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 4, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1042",
                            ProductId = 10,
                            Quantity = 8,
                            QuantityAfter = 4,
                            QuantityBefore = 12,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Sales order #1043",
                            ProductId = 14,
                            Quantity = 6,
                            QuantityAfter = 2,
                            QuantityBefore = 8,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 4, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Network expansion",
                            ProductId = 6,
                            Quantity = 2,
                            QuantityAfter = 6,
                            QuantityBefore = 8,
                            TransactionType = "OUT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 4, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Cabling project bulk",
                            ProductId = 8,
                            Quantity = 70,
                            QuantityAfter = 80,
                            QuantityBefore = 150,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 4, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Monthly supply",
                            ProductId = 9,
                            Quantity = 50,
                            QuantityAfter = 200,
                            QuantityBefore = 250,
                            TransactionType = "OUT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 4, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Training supply",
                            ProductId = 11,
                            Quantity = 5,
                            QuantityAfter = 45,
                            QuantityBefore = 50,
                            TransactionType = "OUT",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10 Nasr City, Cairo, Egypt",
                            ContactPerson = "Ahmed Hassan",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed@techworld.com",
                            IsActive = true,
                            Name = "TechWorld Trading",
                            Phone = "+20-100-123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "55 Dokki St, Giza, Egypt",
                            ContactPerson = "Mona Khalil",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mona@officehub.com",
                            IsActive = true,
                            Name = "Office Hub Co.",
                            Phone = "+20-112-987-6543"
                        },
                        new
                        {
                            Id = 3,
                            Address = "22 Maadi, Cairo, Egypt",
                            ContactPerson = "Karim Samir",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "karim@netgear-eg.com",
                            IsActive = true,
                            Name = "NetGear Solutions",
                            Phone = "+20-115-456-7890"
                        },
                        new
                        {
                            Id = 4,
                            Address = "8 Heliopolis, Cairo, Egypt",
                            ContactPerson = "Layla Ibrahim",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "layla@furnipro.com",
                            IsActive = true,
                            Name = "FurniPro Egypt",
                            Phone = "+20-101-321-6549"
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@inventory.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$JYSOpyPlfpyzJFdzu84gj.pgBxawBpCq4f3UpAxn5ZvgH2PXX9uLm",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara@inventory.com",
                            FullName = "Sara Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$NUfjsYxWhFYiBYsboOKB.u9YeRajBTeI0R3TjEdRob.HYSkTH.tJS",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar@inventory.com",
                            FullName = "Omar Staff",
                            IsActive = true,
                            PasswordHash = "$2a$11$uQcjUfoNO/ILkIYghoCzJOVCDq4ss1.UkXORaEIzEb7kqkmYYaSPq",
                            Role = "Staff"
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Alert", b =>
                {
                    b.HasOne("InventoryAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.HasOne("InventoryAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryAPI.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryAPI.Models.StockTransaction", b =>
                {
                    b.HasOne("InventoryAPI.Models.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("InventoryAPI.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
